import type { Metadata } from "next";
import { Exo_2, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "./_components/NavBar/NavBar";
import Footer from "./_components/Footer/Footer";
import { Toaster } from "sonner";
import WrapperNavber from "../providers/WrapperNavbar";
import TanStackProvider from "@/providers/TanStackProvider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const exo = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${exo.className} antialiased`}>
        <TanStackProvider>
        <div className="w-full">
          {/* navber */}
          
           <WrapperNavber>
            <NavBar/>
            </WrapperNavber>
            {children}
            <Toaster/>
            </div>
             <Footer/>
             </TanStackProvider>
      </body>
    </html>
  );
}